---
driver_config: 
  box: ubuntu-14.04
  box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
driver_plugin: vagrant
platforms: 
  - 
    attributes: 
         kagent:
            dashboard:
               user: "hopagent@sics.se"
               password: "hopagent"
            rest_api:
               user: "hopagent@sics.se"
               password: "hopagent"
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
            dir: "/tmp"
         hopsworks:
            default:
               private_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "true"
    driver_config: 
      customize: 
        memory: 1024
        cpuexecutioncap: 90
        cpus: 1
        natdnshostresolver1: "on"
        natdnsproxy1: "on"
        nictype1: "virtio"
      network: 
        - 
          - private_network
          - 
            ip: "192.168.0.2"
        - ["forwarded_port", {guest: 50070, host: 50071}]

    name: letsgo
    run_list:
      - recipe[kagent::install]
      - recipe[kagent::default]
      - recipe[kagent::test]
suites: 
  - 
    name: default
    run_list: ~

